const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const path = require('path');
dotenv.config();
const mongoose = require('mongoose');
const app = express();
app.use(cors());
app.use(express.json());
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/ozhin_db';
mongoose.connect(MONGODB_URI).then(()=> console.log('Connected to MongoDB')).catch(e=> console.error(e));
const Product = require('./models/Product');
const User = require('./models/User');
const apiRouter = require('./routes/api');
const adminRouter = require('./routes/admin');
app.use('/api', apiRouter);
app.use('/admin', adminRouter);
app.use(express.static(path.join(__dirname, '../frontend')));
app.get('*', (req,res)=> res.sendFile(path.join(__dirname, '../frontend/index.html')));
const PORT = process.env.PORT || 4000;
app.listen(PORT, ()=> console.log('Ozhin server running on', PORT));
